name: 'Deploy'
on:
  push:
    tags:
      - v*

env:
  S3_BUCKET_DEV: shc-verifier-services-dev
  S3_BUCKET_TEST: shc-verifier-services-test
  S3_BUCKET_PROD: shc-verifier-services-prod
  S3_DIR: vci-directory
  LOCAL_SOURCE_FILE: vci-issuers.json
  REGION: us-east-1

jobs:
  deployDev:
    if: contains(github.ref, 'dev')
    name: 'Deploy VCI issuers list to TCP dev'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: 'Configure Dev AWS Role'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        role-to-assume: "arn:aws:iam::789379687343:role/GithubECSRole"
        role-duration-seconds: 1200
        role-session-name: GithubActionsECSDev
    - name: 'Sync issuers file to S3'
      run: |
        pwd
        ls -ahl
        aws s3 sync ${{ env.LOCAL_SOURCE_FILE }} 's3://${{ env.S3_BUCKET_DEV }}/${{ env.S3_DIR }}'

  deployTest:
    if: contains(github.ref, 'test')
    name: 'Deploy VCI issuers list to TCP test'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: 'Configure Dev AWS Role'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        role-to-assume: "arn:aws:iam::789379687343:role/GithubECSRole"
        role-duration-seconds: 1200
        role-session-name: GithubActionsECSDev
    - name: 'Sync issuers file to S3'
      run: |
        aws s3 sync ${{ env.LOCAL_SOURCE_FILE }} 's3://${{ env.S3_BUCKET_TEST }}/${{ env.S3_DIR }}'

  deployProd:
    if: contains(github.ref, '-prod')
    name: 'Deploy VCI issuers list to TCP production'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: 'Configure Dev AWS Role'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        role-to-assume: "arn:aws:iam::789379687343:role/GithubECSRole"
        role-duration-seconds: 1200
        role-session-name: GithubActionsECSDev
    - name: 'Sync issuers file to S3'
      run: |
        aws s3 sync ${{ env.LOCAL_SOURCE_FILE }} 's3://${{ env.S3_BUCKET_PROD }}/${{ env.S3_DIR }}'